apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: tugas8
  name: tugas8
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: tugas8
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: cidam77/tugas8:v1
        name: tugas8
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /go/src/TUGAS8
          name: tugas8-claim0
      hostname: tugas8
      restartPolicy: Always
      volumes:
      - name: tugas8-claim0
        persistentVolumeClaim:
          claimName: tugas8-claim0
status: {}
